ACPICA: hwvalid: Allow writes to port I/O 0x81 - 0x8b
acpica/acpica pull request #817
Opened 2022-12-02 19:25 UTC by superm1

Microsoft introduced support in Windows XP for blocking port I/O to various regions.  For Windows compatibility ACPICA has adopted the same protections and will disallow writes to those (presumably) the same regions.

On some systems the AML included with the firmware will issue 4 byte long writes to 0x80.  These writes aren't making it over because of this blockage. The first 4 byte write attempt is rejected, and then subsequently 1 byte at a time each offset is tried. The first at 0x80 works, but then the next 3 bytes are rejected.

This manifests in bizarre failures for devices that expected the AML to write all 4 bytes.  Trying the same AML on Windows 10 or 11 doesn't hit this failure and all 4 bytes are written.

Either some of these regions were wrong or some point after Windows XP some of these regions blocks have been lifted.

In the last 15 years there doesn't seem to be any reports popping up of this error in the Windows event viewer anymore.  There is no documentation at Microsoft's developer site indicating that Windows ACPI interpreter blocks these regions. Between the lack of documentation and the fact that the writes actually do work in Windows 10 and 11, it's quite likely Windows doesn't actually enforce this anymore.

So to help the issue, drop enforcing protected ranges.

Fixes https://github.com/acpica/acpica/issues/816
Signed-off-by: Mario Limonciello <mario.limonciello@amd.com>

2022-12-08 11:27 UTC, rafaeljw requested changes
I'm not sure it is safe to drop the validation altogether, although quite likely it is overkill on post-XP systems.

I would rather rework it so that the OSI_WIN_XP entries take effect only if nothing newer than XP has been acknowledged via _OSI, but the ALWAYS_ILLEGAL entries should be retained.

2022-12-08 17:27 UTC, superm1 commented
> I'm not sure it is safe to drop the validation altogether, although quite likely it is overkill on post-XP systems.
> 
> I would rather rework it so that the OSI_WIN_XP entries take effect only if nothing newer than XP has been acknowledged via _OSI, but the ALWAYS_ILLEGAL entries should be retained.

OK thanks, I've adjusted accordingly.

2022-12-15 14:51 UTC, rafaeljw approved these changes
This looks good to me now, thank you!

2022-12-15 15:00 UTC, rafaeljw commented
> Thanks! In terms of getting it to Linux, should I port this PR and send something to linux-acpi referencing this PR?

Yes, please.

2023-02-07 18:18 UTC, merged