Fix GCC 12 dangling-pointer warning
acpica/acpica pull request #869
Opened 2023-04-12 16:25 UTC by pprindeville

We're storing a persistent pointer to an ephemeral local variable which technically is a dangling pointer and the compiler is correct. However, since we never indirect the pointer, this is a safe operation and we can suppress the warning.

Also, some C run-times (like MUSL) aren't including <stdint.h> indirectly so we must include it explicitly or we won't have the type definition for uintptr_t.

Fixes issue #867.

2023-04-12 16:36 UTC, sacdintel commented
Hi Philip,
Thanks for your bug report and this PR which hopefully fixes it! Let me review and test it and get back to you!
- Saket Dumbre

2023-04-12 16:59 UTC, sacdintel commented
Philip,
I also had a question/suggestion which you could help us test on GCC 12 and that way we might not need to suppress any warnings using #pragma. 
What if in dbstats.c file towards the end around line number 654 and 655 (new lines) we simply reassign the two pointers to NULL  (AcpiGbl_EntryStackPointer = NULL; and also AcpiGbl_LowestStackPointer = NULL;)? I am not 100% sure if it will resolve the issue but we could give it a fair try I think and also check for functionality/operation retention. Some other pointers which could possibly be dangling can also be tackled in a similar manner. What do you think about this possible solution? I might not be able to test with GCC 12 since my older Ubuntu version might not be able to upgrade beyond GCC 9 or 10 I think. Thanks a lot!

2023-04-12 17:25 UTC, pprindeville commented
I tried your suggestion and it makes no difference, as I anticipated.  The pointer technically begins dangling as soon as `AcpiUtInitStackPtrTrace()` returns and pops its stack frame.

2023-04-12 19:16 UTC, sacdintel commented
OK got it, this is what I had feared would happen or how things worked once we return from the function. So I will go ahead and merge your patch this/next week after confirming things don't break elsewhere in Windows/MSVC env. Thanks for the contribution and please keep us in the loop about any (if) further problems with GCC 12+ versions.

2023-04-12 20:04 UTC, pprindeville commented
> Thanks for the contribution and please keep us in the loop about any (if) further problems with GCC 12+ versions.

You got it!

2023-04-13 22:28 UTC, sacdintel requested changes
Hi Philip,
Unfortunately, I get an error while "making" acpiexec on Cygwin with GCC version 11.3.0

../../../source/components/utilities/utdebug.c:189:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
  189 | #pragma GCC diagnostic ignored "-Wdangling-pointer="
      |                                ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [../Makefile.rules:20: obj/utdebug.o] Error 1

Any idea how to resolve this? Is it a good idea to use an #ifdef for GCC versions 12+ since it looks like the lower versions don't recognize the "-Wdangling-pointer=" warning turned error message?

Update: I managed to seemingly fix it and I am gonna go ahead and add some suggestions to this PR to be included, so that we maintain compatibility with non-GCC systems.   

#if __GNUC__ >= 12
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdangling-pointer="
    AcpiGbl_EntryStackPointer = &CurrentSp;
#pragma GCC diagnostic pop
#else
    AcpiGbl_EntryStackPointer = &CurrentSp;
#endif

2023-04-13 23:59 UTC, pprindeville commented
> Hi Philip, Unfortunately, I get an error while "making" acpiexec on Cygwin with GCC version 11.3.0

Fixed the issue.  Built with 11.3.0 with no warnings.

2023-04-19 00:24 UTC, pprindeville commented
Anything needed from me at this time?

2023-04-19 15:05 UTC, sacdintel commented
Not really, but I will keep you updated if anything is needed. I need to test the updated PR some time this week under various environments and then I can approve and merge this PR. Thanks a lot!

2023-04-19 16:59 UTC, sacdintel approved these changes

2023-04-19 17:00 UTC, merged