os_specific: zephyr: add support for non uefi platform
acpica/acpica pull request #882
Opened 2023-07-06 16:17 UTC by najumon1980

add support for non uefi platform for zephyr rtos

2023-07-07 01:43 UTC, najumon1980 commented
@ acpibob could you please review and merge the PR if ok ?

2023-07-07 09:48 UTC, tbursztyka requested changes
I would revisit this entirely.

Have a function in zephyr side (in include/zephyr/arch/x86/acpi.h) called z_acpi_get_rsdp_phys_addr(), which one will internally call the existing code that you are basically duplicating here: less code to maintain in both projects then. (just store the physical address as well instead of the mapped one only, in zephyr side I mean). 
The code there as been working for years, it is less prone to bug and does not require to bloat the adaptation code in acpica part (which should be as minimal as possible).

2023-07-07 10:07 UTC, najumon1980 commented
> I would revisit this entirely.
> 
> Have a function in zephyr side (in include/zephyr/arch/x86/acpi.h) called z_acpi_get_rsdp_phys_addr(), which one will internally call the existing code that you are basically duplicating here: less code to maintain in both projects then. (just store the physical address as well instead of the mapped one only, in zephyr side I mean). The code there as been working for years, it is less prone to bug and does not require to bloat the adaptation code in acpica part (which should be as minimal as possible).

We are replacing the legacy acpi x86 implementation with acpica (see the draft Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/59917 where the x86/../acpi.c removed). With minimum acpica table initialization (AcpiInitializeTables), we can retrieve most of required tables which is design for pre-kernel initialization. 

ACPICA is already using on multiple OS and hence I believe it is more stable and also need not want worry much about acpi version as platform FW updated to newer versions.

2023-07-11 04:51 UTC, najumon1980 commented
@tbursztyka would like to know whether you got time to review my response ?

2023-07-12 19:16 UTC, sacdintel commented
Is there any other way around to avoid hardcoding the RSDP address and can instead be passed from the Zephyr side? Much of the suggestion from @tbursztyka might help address it but I am not sure of the motive firstly behind moving on from the legacy x86 acpi implementation. Thanks!

2023-07-14 18:49 UTC, sacdintel commented
Let me know what you would like to do. From my end, everything looks good and is ready to be merged. Since it is a major implementation change from the Zephyr side, I hope it is approved by the community and other architects also want to move ahead with this! Thanks!

2023-07-15 18:58 UTC, jhedberg commented
> Let me know what you would like to do. From my end, everything looks good and is ready to be merged. Since it is a major implementation change from the Zephyr side, I hope it is approved by the community and other architects also want to move ahead with this! Thanks!

Since this is not very time critical, I'd suggest to wait until August, when @tbursztyka is back from vacation (I'll also be off for the next two weeks). Then we can make sure that we have proper consensus among the upstream Zephyr maintainers before proceeding with the changes.

2023-07-17 04:29 UTC, najumon1980 commented
> Let me know what you would like to do. From my end, everything looks good and is ready to be merged. Since it is a major implementation change from the Zephyr side, I hope it is approved by the community and other architects also want to move ahead with this! Thanks!

@sacdintel I will discuss Zephyr arch change in Zephyr Architecture Working Group and will update you once it got approval (although this PR will not impact/break existing functionalities).

2023-07-17 22:04 UTC, sacdintel commented
Sounds good guys! Take your time, no rush! Thanks for the updates!

2023-08-09 08:43 UTC, tbursztyka commented
The problem I see with this is that it bring even more zephyr API usage into an external code. So more maintenance hassle. 
Thus why I think it's better to keep it as minimal as possible. Get the rsdp pointer function from zephyr and call it here, instead of coding it here: less exposure of zephyr API, less risk of api changes affecting this code then, etc etc... not to mention the configuration option from zephyr, as well as the x86 bios stuff btw: which makes this code not zephyr arch-agnostic anymore.

2023-08-16 03:36 UTC, najumon1980 commented
> The problem I see with this is that it bring even more zephyr API usage into an external code. So more maintenance hassle. Thus why I think it's better to keep it as minimal as possible. Get the rsdp pointer function from zephyr and call it here, instead of coding it here: less exposure of zephyr API, less risk of api changes affecting this code then, etc etc... not to mention the configuration option from zephyr, as well as the x86 bios stuff btw: which makes this code not zephyr arch-agnostic anymore.

Then the entire OS abstraction layer need to move to Zephyr repo. I can move  if you think source/os_specific/service_layers/oszephyr.c is better to be part of Zephyr.

2023-08-16 08:04 UTC, jhedberg commented
> Then the entire OS abstraction layer need to move to Zephyr repo. I can move if you think source/os_specific/service_layers/oszephyr.c is better to be part of Zephyr.

Could you elaborate a bit on that logic? I think Tomasz is just suggesting to keep the `oszephyr.c` code and set of Zephyr APIs we depend on minimal, but not getting rid of it entirely. I believe ACPICA is designed so that each supported OS has an adaption layer as part of  the ACPICA tree - not outside of it.

2023-08-21 08:00 UTC, tbursztyka commented
Indeed, I am not proposing to ditch oszephyr.c at all. What I want is:
- a public z_arch_acpi_rsdp_lookup() function on zephyr side (it's really easy to implement since the code already exists for x86 in arch/x86/core/acpi.c) 
- then in present oszephyr.c, use that function to get rsdp

result: No x86, no EFI, no BIOS, not too much zephyr API etc... exposure into acpica.

2023-08-21 12:58 UTC, tbursztyka requested changes

2023-08-21 12:58 UTC, tbursztyka commented on source/os_specific/service_layers/oszephyr.c
> +#if defined(CONFIG_X86_EFI)
No you are still bringing CONFIG_X86_EFI from zephyr. Just get a unique function from zephyr to call, as proposed

2023-08-22 07:27 UTC, tbursztyka requested changes
ok now it's fine.

2023-08-24 16:08 UTC, sacdintel commented
Is this PR ready for our review and testing? Please let me know, thanks!

2023-09-01 06:08 UTC, jhedberg approved these changes

2023-09-01 06:22 UTC, tbursztyka approved these changes

2023-09-01 06:38 UTC, jhedberg commented
@sacdintel from our side the PR ready now i.e. feel free to do a final review & merge it if it looks good.

2023-09-05 05:33 UTC, najumon1980 commented
@sacdintel could you please review and merge if OK

2023-09-06 17:58 UTC, sacdintel commented
Looks good, thanks guys!

2023-09-06 17:58 UTC, merged